# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

CLIENT_ID: 397109623010-6mp9curgdesv4gh2gqolecoslhra0rg1.apps.googleusercontent.com
CLIENT_SECRET: PaQI2o9r_Vmsub_MBcJme4gL
CODE_RECEIVED: 4/bzRbAXZ_X58bySDzOYWpXrY5IQPRs3TsjJygqwTYm0c
TEST_NUMBER: "1000"


LAST_ARTICLE_URL: https://medium.com/@roadstr_cars/5-bonnes-raisons-de-rouler-en-porsche-912-37c4db5fef4b

S3_BUCKET_NAME: roadstr
AWS_ACCESS_KEY_ID: AKIAJ5DPCFSAXBA4YTPA
AWS_SECRET_ACCESS_KEY: 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

MANGOPAY_PRODUCTION: false
MANGOPAY_CLIENT_ID: jeromeborenstejn
MANGOPAY_CLIENT_PASSPHRASE: OH1bg5fYUuYTuXyo5kqQuc8tg2nrSth5jTFSvK7agnba87NNQo

GOOGLE_API_KEY: AIzaSyDMg1a7WACapnyk8QK9GihNBFl08SwxJqE
# AIzaSyDMg1a7WACapnyk8QK9GihNBFl08SwxJqE


development:
  FB_ID: "818328528208508"
  FB_SECRET: "f028e45daeeddc44e21eb166b022d45f"
  SEGMENT_WRITE_KEY: wu4GjkzhaoFG5e2VKcfFizV84nQsQfex

# production:
#   FB_ID: "818328528208508"
#   FB_SECRET: "f028e45daeeddc44e21eb166b022d45f"


MANDRILL_APIKEY: Wn5o5L0iJGzaj-31qn_9HA
MANDRILL_USERNAME: app28873985@heroku.com

MAILCHIMP_API_KEY: '0127cd68877d095b3a75ba1f662377a5-us9'
MAILCHIMP_LIST_ID: 'fda95e9782'

ALGOLIA_APP_ID: 'IISI9UGNVS'
ALGOLIA_ADMIN_API_KEY: '9484917e96e7d4dfa8cf326c55098271'
ALGOLIA_SEARCH_API_KEY: 'a3370a05eeb0df4565ec1df1455fe529'
# ALGOLIA_ADMIN_API_KEY: '2152f9cf78ea6b83c30e698edcb1b58d'
# ALGOLIA_SEARCH_API_KEY: '2413a7053fb2e4026a016baebf3b3406'


TWILIO_ACCOUNT_SID: AC1acfdbb1176da5d477cc33f2168455bb
TWILIO_AUTH_TOKEN: 2ad2f634a4996e7bfa5f7cb8f14befa8

ROADSTR_DEV: true



