# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7895d488dd801d1782fa9d2254515eacf911dbc5d4ad4166e8d422181f1b72a4e389b2e580f760704a2e3631c17a87a6b38a1d67bb09cc18798f91c659a34a4

test:
  secret_key_base: dd81836d3e50abb1044e3282c7f73d66b8f5b41d6059c3b75d3b69271c0c9758e9acc7d6d91b65b3bdaa2d8633dff6c70d836d8919ce4f05c868d7502cde4737

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
